name: Python Linting

on:
  push:
  pull_request:

jobs:
  build:
    name: Python Linting
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Install Python Deps
      run: python3 -m pip install flake8

    - name: Lint MicroPython Examples
      shell: bash
      run: |
        python3 -m flake8 --show-source --ignore E501 examples/micropython

    - name: Lint Cosmic Unicorn Libs
      shell: bash
      run: |
        python3 -m flake8 --show-source --ignore E501 firmware/PIMORONI_COSMIC_UNICORN/lib

    - name: Lint Galactic Unicorn Libs
      shell: bash
      run: |
        python3 -m flake8 --show-source --ignore E501 firmware/PIMORONI_GALACTIC_UNICORN/lib